<a href="https://colab.research.google.com/github/vaniamudan/AIML/blob/main/tensor_datatypes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import drive
drive.mount('/content/drive')


Mounted at /content/drive


In [ ]:
import tensorflow as tf

In [ ]:
t=tf.constant(4)
print(t)

tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
t=tf.constant([2.0,3.0,4.0])
print(t)

tf.Tensor([2. 3. 4.], shape=(3,), dtype=float32)


In [ ]:
t=tf.constant([[1,2],
              [3,4],
              [5,6]])
print(t)

tf.Tensor(
[[1 2]
 [3 4]
 [5 6]], shape=(3, 2), dtype=int32)


In [ ]:
t=tf.constant([
    [[0,1,2,3,4],
    [5,6,7,8,9]
    ],
    [[10,11,12,13,14],
    [15,16,17,18,19]],
    [[20,21,22,23,24],
    [25,26,27,28,29]]
])
print(t)

tf.Tensor(
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]]

 [[10 11 12 13 14]
  [15 16 17 18 19]]

 [[20 21 22 23 24]
  [25 26 27 28 29]]], shape=(3, 2, 5), dtype=int32)


In [ ]:
x=tf.constant(4)
print("dimension",tf.rank(x).numpy())
print(x)

dimension 0
tf.Tensor(4, shape=(), dtype=int32)


In [ ]:
x1=tf.ones([2,])
print("dimension",tf.rank(x1).numpy())
print(x1)

dimension 1
tf.Tensor([1. 1.], shape=(2,), dtype=float32)


In [ ]:
x2=tf.ones([2,3])
print("dimension",tf.rank(x2).numpy())
print(x2)

dimension 2
tf.Tensor(
[[1. 1. 1.]
 [1. 1. 1.]], shape=(2, 3), dtype=float32)


In [ ]:
x3=tf.ones([2,2,3])
print("dimension",tf.rank(x3).numpy())
print(x3)

dimension 3
tf.Tensor(
[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]], shape=(2, 2, 3), dtype=float32)


In [ ]:
a=tf.Variable(35)
b=tf.Variable([[[0,1,2],[3,4,5]],[[6,7,8],[9,10,11]]])
print(a)
print(b)

<tf.Variable 'Variable:0' shape=() dtype=int32, numpy=35>
<tf.Variable 'Variable:0' shape=(2, 2, 3) dtype=int32, numpy=
array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)>


In [ ]:
a.assign(20)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=20>

In [ ]:
x.assign(3)

AttributeError: 'tensorflow.python.framework.ops.EagerTensor' object has no attribute 'assign'

In [ ]:
y=tf.reshape(b,[1,12])

In [ ]:
y

<tf.Tensor: shape=(1, 12), dtype=int32, numpy=array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11]], dtype=int32)>

In [ ]:
z=tf.reshape(b,[12,1])

In [ ]:
z

<tf.Tensor: shape=(12, 1), dtype=int32, numpy=
array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]], dtype=int32)>

In [ ]:
a.numpy()

20

In [ ]:
b.numpy()

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]], dtype=int32)

In [ ]:
tf.rank(a)

<tf.Tensor: shape=(), dtype=int32, numpy=0>

In [ ]:
tf.rank(b)

<tf.Tensor: shape=(), dtype=int32, numpy=3>

In [ ]:
#slicing
t1=b[1,1,2]

In [ ]:
t1

<tf.Tensor: shape=(), dtype=int32, numpy=11>

In [ ]:
t2=b[0,1,1]
t2

<tf.Tensor: shape=(), dtype=int32, numpy=4>

In [ ]:
d=tf.constant([0,1,1,2,3,5,8,13,21,34])
d

<tf.Tensor: shape=(10,), dtype=int32, numpy=array([ 0,  1,  1,  2,  3,  5,  8, 13, 21, 34], dtype=int32)>

In [ ]:
print("all values",d[0:9].numpy())

all values [ 0  1  1  2  3  5  8 13 21]


In [ ]:
print("first value",d[2:4].numpy())

first value [1 2]


In [ ]:
print("last value",d[:4].numpy())

last value [0 1 1 2]


In [ ]:
print("last value",d[4:].numpy())

last value [ 3  5  8 13 21 34]


In [ ]:
print("last value",d[2:8].numpy())

last value [ 1  2  3  5  8 13]


In [ ]:
print("last value",d[::-1].numpy())

last value [34 21 13  8  5  3  2  1  1  0]


In [ ]:
d1=tf.cast(d,dtype=tf.float64)
d1

<tf.Tensor: shape=(10,), dtype=float64, numpy=array([ 0.,  1.,  1.,  2.,  3.,  5.,  8., 13., 21., 34.])>

In [ ]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
c = tf.subtract(a,b)
print(c)

tf.Tensor(
[[-4 -4]
 [-4 -4]], shape=(2, 2), dtype=int32)


In [ ]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
c = tf.add(a,b)
print(c)

tf.Tensor(
[[ 6  8]
 [10 12]], shape=(2, 2), dtype=int32)


In [ ]:
a = tf.constant([[1,2],[3,4]])
b = tf.constant([[5,6],[7,8]])
c = tf.matmul(a,b)
print(c)

tf.Tensor(
[[19 22]
 [43 50]], shape=(2, 2), dtype=int32)


In [ ]:
d = tf.square(a)
print(d)

tf.Tensor(
[[ 1  4]
 [ 9 16]], shape=(2, 2), dtype=int32)


In [ ]:
matrix1 = tf.constant([[4, 2, 4], [1, 4, 3], [4, 2, 1]])

# Count number of 4s in each matrix
count1 = tf.reduce_sum(tf.cast(tf.equal(matrix1, 4), tf.int32))

print("Matrix 1:")
print(matrix1.numpy())
print(f"Number of 4s: {count1.numpy()}\n")

Matrix 1:
[[4 2 4]
 [1 4 3]
 [4 2 1]]
Number of 4s: 4



In [ ]:
a=tf.constant([[2,3,4],[9,6,7],[4,3,6]])
b=tf.constant([[9,3,3],[2,1,0],[2,4,5]])

In [ ]:
import tensorflow as tf
# Define matrices A and B as TensorFlow constants
A = tf.constant([[2, 3, 4],
                 [9, 6, 7],
                 [4, 3, 6]])
B = tf.constant([[9, 3, 3],
                 [2, 1, 0],
                 [2, 4, 5]])
# Calculate the sum of diagonals using tf.linalg.trace
diag_sum_A = tf.linalg.trace(A)  # Primary diagonal sum of A
diag_sum_B = tf.linalg.trace(B)  # Primary diagonal sum of B
# Compare diagonal sums and find the matrix with the larger sum
larger_matrix = tf.cond(diag_sum_A > diag_sum_B,
                        lambda: "A",
                        lambda: "B")
max_value = tf.maximum(diag_sum_A, diag_sum_B)
# Print the result
print(f"Matrix: {larger_matrix}, Value: {max_value.numpy()}")

Matrix: B, Value: 15


In [ ]:
x=tf.constant([1,2,3,4,5,6])
print(x)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
x=tf.Variable([1,2,3,4,5,6])
print(x.name)
print(x.numpy())
print(x.dtype)

Variable:0
[1 2 3 4 5 6]
<dtype: 'int32'>


In [ ]:
x1=tf.constant([1,2,3,4,5,6],shape=(2,3))
print(x1)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x1=tf.constant([1,2,3,4,5,6])
x2=tf.reshape(x1,(2,3))
print(x2)

tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
#convert the whole data into 1d
x3=tf.constant([[1,2,3],[4,5,6]])
print(x3)


tf.Tensor(
[[1 2 3]
 [4 5 6]], shape=(2, 3), dtype=int32)


In [ ]:
x3=tf.constant([[1,2,3],[4,5,6]],shape=(6))
print(x3)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
x3=tf.constant([[1,2,3],[4,5,6]])
x4=tf.reshape(x3,(6))
print(x4)

tf.Tensor([1 2 3 4 5 6], shape=(6,), dtype=int32)


In [ ]:
v=tf.constant([[[1,2,3],[4,5,6],[7,8,9]],[[10,11,12],[13,14,15],[16,17,18]]])

In [ ]:
v

<tf.Tensor: shape=(2, 3, 3), dtype=int32, numpy=
array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]], dtype=int32)>

In [ ]:
#slicing
r=tf.slice(v,[0,1,0],[1,1,1])
print(r)

tf.Tensor([[[4]]], shape=(1, 1, 1), dtype=int32)


In [ ]:
w=tf.constant([4,3,6,2,7,8])
a=tf.gather(w,[2])
print(a)

tf.Tensor([6], shape=(1,), dtype=int32)


In [ ]:
w=tf.constant([4,3,6,2,7,8])
a=tf.gather(w,[0,3])
print(a)

tf.Tensor([4 2], shape=(2,), dtype=int32)


In [ ]:
w=tf.constant([4,3,6,2,7,8])
a=tf.gather(w,indices=[1])
print(a)

tf.Tensor([3], shape=(1,), dtype=int32)


In [ ]:
n=tf.constant([[4,3,6],[2,7,8]])
print(n)

tf.Tensor(
[[4 3 6]
 [2 7 8]], shape=(2, 3), dtype=int32)


In [ ]:
# to chk max element in a tensor
print(tf.reduce_max(n))

tf.Tensor(8, shape=(), dtype=int32)


In [ ]:
print(tf.reduce_min(n))

tf.Tensor(2, shape=(), dtype=int32)


In [ ]:
#concatenation
m=tf.constant([[1,2,3],[4,5,6]])
n=tf.constant([[7,8,9],[10,11,12]])
f=tf.concat([m,n],axis=0)
print(f)

tf.Tensor(
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]], shape=(4, 3), dtype=int32)


In [ ]:
tf.concat([m,n],axis=1)

<tf.Tensor: shape=(2, 6), dtype=int32, numpy=
array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]], dtype=int32)>